package demo.entity;
// Generated Jul 25, 2017 2:56:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "album", catalog = "db_music")
public class Album implements java.io.Serializable {

	private Integer id;
	private String albumId;
	private String albumName;
	private Set<Songs> songses = new HashSet<Songs>(0);

	public Album() {
	}

	public Album(String albumId, String albumName) {
		this.albumId = albumId;
		this.albumName = albumName;
	}

	public Album(String albumId, String albumName, Set<Songs> songses) {
		this.albumId = albumId;
		this.albumName = albumName;
		this.songses = songses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "albumId", nullable = false, length = 50)
	public String getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(String albumId) {
		this.albumId = albumId;
	}

	@Column(name = "albumName", nullable = false, length = 50)
	public String getAlbumName() {
		return this.albumName;
	}

	public void setAlbumName(String albumName) {
		this.albumName = albumName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "album")
	public Set<Songs> getSongses() {
		return this.songses;
	}

	public void setSongses(Set<Songs> songses) {
		this.songses = songses;
	}

}
