package demo.entity;
// Generated Jul 25, 2017 2:56:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name = "genre", catalog = "db_music")
public class Genre implements java.io.Serializable {

	private Integer id;
	private String genreId;
	private String genreName;
	private Set<Songs> songses = new HashSet<Songs>(0);

	public Genre() {
	}

	public Genre(String genreId, String genreName) {
		this.genreId = genreId;
		this.genreName = genreName;
	}

	public Genre(String genreId, String genreName, Set<Songs> songses) {
		this.genreId = genreId;
		this.genreName = genreName;
		this.songses = songses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "genreId", nullable = false, length = 50)
	public String getGenreId() {
		return this.genreId;
	}

	public void setGenreId(String genreId) {
		this.genreId = genreId;
	}

	@Column(name = "genreName", nullable = false, length = 100)
	public String getGenreName() {
		return this.genreName;
	}

	public void setGenreName(String genreName) {
		this.genreName = genreName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genre")
	public Set<Songs> getSongses() {
		return this.songses;
	}

	public void setSongses(Set<Songs> songses) {
		this.songses = songses;
	}

}
