package demo.entity;
// Generated Jul 11, 2017 6:17:00 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vn generated by hbm2java
 */
@Entity
@Table(name = "vn", catalog = "db_kara")
public class Vn implements java.io.Serializable {

	private Integer id;
	private Album album;
	private Volume volume;
	private String ten;
	private int maso;
	private String loi;
	private String thongtin;
	private String linkyoutube;
	private Integer masauso;
	private Boolean baihatyeuthich;
	private Boolean baihatnoibat;
	private String loidaydu;

	public Vn() {
	}

	public Vn(Album album, Volume volume, String ten, int maso, String loi, String thongtin) {
		this.album = album;
		this.volume = volume;
		this.ten = ten;
		this.maso = maso;
		this.loi = loi;
		this.thongtin = thongtin;
	}

	public Vn(Album album, Volume volume, String ten, int maso, String loi, String thongtin, String linkyoutube,
			Integer masauso, Boolean baihatyeuthich, Boolean baihatnoibat, String loidaydu) {
		this.album = album;
		this.volume = volume;
		this.ten = ten;
		this.maso = maso;
		this.loi = loi;
		this.thongtin = thongtin;
		this.linkyoutube = linkyoutube;
		this.masauso = masauso;
		this.baihatyeuthich = baihatyeuthich;
		this.baihatnoibat = baihatnoibat;
		this.loidaydu = loidaydu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idalbum", nullable = false)
	public Album getAlbum() {
		return this.album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vol_id", nullable = false)
	public Volume getVolume() {
		return this.volume;
	}

	public void setVolume(Volume volume) {
		this.volume = volume;
	}

	@Column(name = "ten", nullable = false, length = 100)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "maso", nullable = false)
	public int getMaso() {
		return this.maso;
	}

	public void setMaso(int maso) {
		this.maso = maso;
	}

	@Column(name = "loi", nullable = false, length = 100)
	public String getLoi() {
		return this.loi;
	}

	public void setLoi(String loi) {
		this.loi = loi;
	}

	@Column(name = "thongtin", nullable = false, length = 100)
	public String getThongtin() {
		return this.thongtin;
	}

	public void setThongtin(String thongtin) {
		this.thongtin = thongtin;
	}

	@Column(name = "linkyoutube", length = 65535)
	public String getLinkyoutube() {
		return this.linkyoutube;
	}

	public void setLinkyoutube(String linkyoutube) {
		this.linkyoutube = linkyoutube;
	}

	@Column(name = "masauso")
	public Integer getMasauso() {
		return this.masauso;
	}

	public void setMasauso(Integer masauso) {
		this.masauso = masauso;
	}

	@Column(name = "baihatyeuthich")
	public Boolean getBaihatyeuthich() {
		return this.baihatyeuthich;
	}

	public void setBaihatyeuthich(Boolean baihatyeuthich) {
		this.baihatyeuthich = baihatyeuthich;
	}

	@Column(name = "baihatnoibat")
	public Boolean getBaihatnoibat() {
		return this.baihatnoibat;
	}

	public void setBaihatnoibat(Boolean baihatnoibat) {
		this.baihatnoibat = baihatnoibat;
	}

	@Column(name = "loidaydu", length = 65535)
	public String getLoidaydu() {
		return this.loidaydu;
	}

	public void setLoidaydu(String loidaydu) {
		this.loidaydu = loidaydu;
	}

}
