package demo.entity;
// Generated Jul 17, 2017 11:35:07 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BorrowId generated by hbm2java
 */
@Embeddable
public class BorrowId implements java.io.Serializable {

	private int employeeId;
	private int equipmentId;

	public BorrowId() {
	}

	public BorrowId(int employeeId, int equipmentId) {
		this.employeeId = employeeId;
		this.equipmentId = equipmentId;
	}

	@Column(name = "employee_id", nullable = false)
	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "equipment_id", nullable = false)
	public int getEquipmentId() {
		return this.equipmentId;
	}

	public void setEquipmentId(int equipmentId) {
		this.equipmentId = equipmentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BorrowId))
			return false;
		BorrowId castOther = (BorrowId) other;

		return (this.getEmployeeId() == castOther.getEmployeeId())
				&& (this.getEquipmentId() == castOther.getEquipmentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEmployeeId();
		result = 37 * result + this.getEquipmentId();
		return result;
	}

}
