package demo.entity;
// Generated Jul 17, 2017 11:35:07 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Equipment generated by hbm2java
 */
@Entity
@Table(name = "equipment", catalog = "db_equipment")
public class Equipment implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String equipmentId;
	private String equipmentName;
	private String status;
	private int quantity;
	private String unit;
	private int categoryId;

	public Equipment() {
	}

	public Equipment(Category category, String equipmentId, String equipmentName, int quantity, String unit,
			int categoryId) {
		this.category = category;
		this.equipmentId = equipmentId;
		this.equipmentName = equipmentName;
		this.quantity = quantity;
		this.unit = unit;
		this.categoryId = categoryId;
	}

	public Equipment(Category category, String equipmentId, String equipmentName, String status, int quantity,
			String unit, int categoryId) {
		this.category = category;
		this.equipmentId = equipmentId;
		this.equipmentName = equipmentName;
		this.status = status;
		this.quantity = quantity;
		this.unit = unit;
		this.categoryId = categoryId;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "category"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "equipment_id", nullable = false, length = 100)
	public String getEquipmentId() {
		return this.equipmentId;
	}

	public void setEquipmentId(String equipmentId) {
		this.equipmentId = equipmentId;
	}

	@Column(name = "equipment_name", nullable = false, length = 100)
	public String getEquipmentName() {
		return this.equipmentName;
	}

	public void setEquipmentName(String equipmentName) {
		this.equipmentName = equipmentName;
	}

	@Column(name = "status", length = 250)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "unit", nullable = false, length = 100)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "category_id", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

}
