package demo.entity;
// Generated Jul 18, 2017 11:37:46 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Borrow generated by hbm2java
 */
@Entity
@Table(name = "borrow", catalog = "db_equipment")
public class Borrow implements java.io.Serializable {

	private Integer id;
	private Equipment equipment;
	private User user;
	private Date dateBorrow;
	private Date dateReturnback;
	private int quantity;
	private boolean status;

	public Borrow() {
	}

	public Borrow(Equipment equipment, User user, Date dateBorrow, Date dateReturnback, int quantity, boolean status) {
		this.equipment = equipment;
		this.user = user;
		this.dateBorrow = dateBorrow;
		this.dateReturnback = dateReturnback;
		this.quantity = quantity;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipment_id", nullable = false)
	public Equipment getEquipment() {
		return this.equipment;
	}

	public void setEquipment(Equipment equipment) {
		this.equipment = equipment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_borrow", nullable = false, length = 10)
	public Date getDateBorrow() {
		return this.dateBorrow;
	}

	public void setDateBorrow(Date dateBorrow) {
		this.dateBorrow = dateBorrow;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_returnback", nullable = false, length = 10)
	public Date getDateReturnback() {
		return this.dateReturnback;
	}

	public void setDateReturnback(Date dateReturnback) {
		this.dateReturnback = dateReturnback;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
