package demo.entity;
// Generated Jul 7, 2017 5:05:55 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vn generated by hbm2java
 */
@Entity
@Table(name = "vn", catalog = "db_kara")
public class Vn implements java.io.Serializable {

	private Integer id;
	private String ten;
	private int maso;
	private String loi;
	private String thongtin;
	private String linkyoutube;
	private String picture;

	public Vn() {
	}

	public Vn(String ten, int maso, String loi, String thongtin) {
		this.ten = ten;
		this.maso = maso;
		this.loi = loi;
		this.thongtin = thongtin;
	}

	public Vn(String ten, int maso, String loi, String thongtin, String linkyoutube, String picture) {
		this.ten = ten;
		this.maso = maso;
		this.loi = loi;
		this.thongtin = thongtin;
		this.linkyoutube = linkyoutube;
		this.picture = picture;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ten", nullable = false, length = 100)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "maso", nullable = false)
	public int getMaso() {
		return this.maso;
	}

	public void setMaso(int maso) {
		this.maso = maso;
	}

	@Column(name = "loi", nullable = false, length = 100)
	public String getLoi() {
		return this.loi;
	}

	public void setLoi(String loi) {
		this.loi = loi;
	}

	@Column(name = "thongtin", nullable = false, length = 100)
	public String getThongtin() {
		return this.thongtin;
	}

	public void setThongtin(String thongtin) {
		this.thongtin = thongtin;
	}

	@Column(name = "linkyoutube", length = 65535)
	public String getLinkyoutube() {
		return this.linkyoutube;
	}

	public void setLinkyoutube(String linkyoutube) {
		this.linkyoutube = linkyoutube;
	}

	@Column(name = "picture", length = 65535)
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

}
